### PR TITLE
Make this the final state of version 1.0.0

### PR DESCRIPTION
**Pull request by DRollin**
I think it would be good to fix this as version 1.0.0, then this is compatible with Ferrite 1.0 and I can make small updates to keep up with Ferrite#master.

### CODE REVIEW

**Comment by DRollin** [comment]
So far, I just changed the version in the project file.
I also need to create a release on github, right?
Anything else that needs to be done?

**Comment by fredrikekre** [comment]
>  I also need to create a release on github, right?

This is done automatically by [TagBot](https://github.com/JuliaRegistries/TagBot)

>  Anything else that needs to be done?

You should
1. Merge this PR
2. Comment on the latest commit on the main branch, see https://github.com/JuliaRegistries/Registrator.jl/blob/master/README.md#via-the-github-app (but you can start from step 3).

**Comment by DRollin** [comment]
Thanks a lot :+1:

**Comment by DRollin** [comment]
@JuliaRegistrator register()

**Review by DRollin — COMMENTED** [review]
@JuliaRegistrator register()

**Pull request merged**
